import type { Metadata } from "next";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Flex, Theme } from "@radix-ui/themes";
import Sidebar from "@/layout/sidebar";
import Content from "@/layout/content";

export const metadata: Metadata = {
  title: "The Lazy Movie DB",
  description: "Generated by boredom",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Lemon&family=Poppins:wght@400;500;600&family=Readex+Pro:wght@400;500;600&display=swap"
          rel="stylesheet"
        />
      </head>

      <body>
        <Theme>
          <Flex direction="row">
            <Sidebar />
            <Content>{children}</Content>
          </Flex>
        </Theme>
      </body>
    </html>
  );
}
